export const GET_ALL = 'publications_get_all'
export const LOADING = 'publications_loading'
export const ERROR = 'publications_error'
export const UPDATE = 'publications_update'
export const COM_LOADING = 'comments_loading'
export const COM_ERROR = 'comments_error'
export const COM_UPDATE = 'comments_update'