export const GET_ALL = 'tasks_get_all'
export const LOADING = 'tasks_loading'
export const ERROR = 'tasks_error'
export const SAVE = 'tasks_save'
export const UPDATE = 'tasks_update'
export const CHANGE_USER_ID = 'tasks_change_user_id'
export const CHANGE_TITLE = 'tasks_change_title'
export const CLEAN = 'tasks_clean'